name: lint-format-docs_update
on: push
jobs:
  lint-format-docs_update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: package installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update docs
        run: |
          pdoc --html -o docs --force ./selenium_helper/selenium_helper.py
          mv --force docs/selenium_helper.html docs/index.html
      - name: Format by black
        run: |
          pip install black
          black selenium_helper
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git status
          git commit -m 'docs update & format by black'
          git push
      - name: Run flake8 test
        run: |
          pip install flake8
          cd selenium_helper
          flake8 --max-line-length 150
